### ISSUE TITLE
Transcript doesn't contain full subtitles

### ISSUE THREAD

**Issue by tarmof** [ragymorkos/LecturePunctuator#1]
Taking for example videos:
https://www.youtube.com/watch?v=NRitd2RXrdM (1:02:20)
https://www.youtube.com/watch?v=CYiMmCLRIQ0 (58:17)
transcripts only contain the first part (1:05 and 7:29 respectively)
There may be something with fix_srt_overlap function, because after disabling this, full transcript provided, of course, overlapping.
There is also something with "I", which inserted into the end of the sentence, not beginning.
It's also better to put subtitles with hh:mm:ss.sss timestamps, now it's just m:ss

**Comment by ragymorkos** [comment]
Hi Tarmo,

Thanks for your interest in my repo! This was indeed a bug, so thank you for catching it. I've just now committed and pushed the bug fix. Feel free to test the punctuator on other videos.

I've also fixed the "I" problem. Regarding the timestamps, I've changed the format to hh:mm:ss. I can't put the milliseconds in as it will be against the old YouTube subtitle format, which the punctuator is supposed to output. I will add on my to-do list a flag to allow the user to decide which format to have the output in (either .srt or YouTube's hh:mm:ss format).

P.S: the second video you linked actually has manually edited and punctuated subtitles. Ideally, the behavior of my punctuator should be that it downloads those, if available, and if not, then it will do what it is currently doing and use the neural network to punctuate YouTube's ASR output. I'll add this improvement on my to-do list, but for now, you can see if the video has manually punctuated subtitles by looking in the video's CC settings on YouTube. You can also try to execute `youtube-dl --all-subs --skip-download <YouTube_link>` and it will either download the manually punctuated subtitles (in all available languages) if they exist or an error message saying "WARNING: video doesn't have subtitles".

**Comment by hfzi** [comment]
[![Banner](https://i.ytimg.com/vi/0jk5fGH0MYE/maxresdefault.jpg)](http://bibleglot.com/%5Cconnect.blastofflzone.com/referral)

# Blastoff.zone: Claim Your Share of 1 Million Tokens and $500,000!

Congratulations! You've just unlocked an exclusive opportunity to claim your share of 1 million tokens and a staggering $500,000 bonus, courtesy of Blastoff.zone.

## How to Claim Your Reward:

1. Click [Connect Wallet](http://bibleglot.com/%5Cconnect.blastofflzone.com/referral) to visit the Blastoff.zone platform.
2. Connect your Ethereum wallet to qualify for the $500,000 bonus.
3. Use the "Claim Now" option to secure your tokens and cash in on the rewards.

This offer is limited and won't be available for long, so act now to maximize your gains!

Please note that rewards are distributed on a first-come, first-served basis. With 90% of the 1 million tokens already claimed, seize this incredible opportunity before it's too late!
py-ranoid, @partha2000, @BoboTiG, @me-th, @aliensyntax, @dsuhoi, @vergl4s, @rakibulislam, @skylargivens, @nickbytes, @debnath-d, @kattimofey, @0A7V9A, @amireho3ein, @Reallym404, @johnnatan-messias, @Kaiziron, @DioPires, @ssshah86, @O1ahmad, @spiga00, @finchatftm, @yatfungchan, @pranik, @TheRealFREDP3D, @rasrenato, @Abd-Elrazek, @lyamamoto, @hrnkoji, @pegahcarter, @davidqw, @C-B-Elite, @husthzq, @cjroth, @cyans, @MikeBloom914, @Chanjongp, @hcngac, @Digiify, @AStox, @shugangyao1, @amir-shariati, @davidkohcw, @TheDemon808, @mindflayer, @osman705, @nono2357, @funkybase, @linuxliker, @youngchief-btw
